<style>
  .data input{
    height: 30px;
    border-radius: 5px;
    border:1px solid #ddd;
    padding-left: 10px;
  }
  .data label{
    margin-top:5px;
  }
  th, td{
    text-align: center;
  }
</style>

<?php View::content() ?>


<div class="titulo-proyectos">RECURSOS (<?php echo count($recursos) ?>)</div>

<section class="data">
      <fieldset style="margin:5px;">
          <table class="table table-striped datatable" style="font-size:12px;">
            <thead>
              <th style="width:10%;">Id</th>
              <th style="text-align:center;">ABR</th>
              <th>Nombre</th>
              <th>Categoría</th>
              <th>Cantidad</th>
              <th>Costo U. (Bs.F)</th>
              <th>Editar</th>
              <th>Eliminar</th>
            </thead>
            <?php foreach ($recursos as $value): ?>
               <tr>         
                   <td><?php echo $value->id ?></td>
                   <td><?php echo $value->abreviatura ?></td>
                   <td><?php echo $value->nombre ?></td>
                   <td><?php $buscar_categoria = Load::model("categorias")->find($value->categorias_id); echo $buscar_categoria->nombre ?></td>
                  <td><?php echo $value->cantidad ?></td>
                  <td><?php echo $value->costo ?></td>
                   <?php $id=$value->id; ?>
                   <td><?php echo Html::link("proyectos/editar_recurso/$id","<span class='glyphicon glyphicon-edit'><span>") ?></td>
                   <td><?php echo Js::link("proyectos/eliminar_recurso/$id","<span class='glyphicon glyphicon-remove-circle'></span>","¿Esta seguro de eliminar este recurso?") ?></td>
                </tr>
            <?php endforeach ?>
          </table>
      </fieldset>
    </section>
