<style>
  .data input{
    height: 30px;
    border-radius: 5px;
    border:1px solid #ddd;
    padding-left: 10px;
  }
  .data label{
    margin-top:5px;
  }
</style>

<?php View::content() ?>

<div class="titulo-proyectos">LISTADO DE CLIENTES (<?php echo count($clientes) ?>)</div>

<section class="data">
      <fieldset style="margin:5px;">
          <table class="table table-striped datatable" style="font-size:12px;">
            <thead>
              <th style="text-align:center;">Id</th>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Teléfonos</th>
              <th>Contacto</th>
              <th>Dirección</th>
              <th>Descripción</th>
              <th>Editar</th>
              <th>Eliminar</th>
            </thead>
            <?php foreach ($clientes as $value): ?>
               <tr>
                   <td style="text-align:center;"><?php echo $value->id ?></td>
                   <td><?php echo $value->nombre ?></td>
                   <td><?php echo $value->correo; ?></td>
                   <td><?php echo $value->telefonos ?></td>
                   <td><?php echo $value->contacto ?></td>
                   <td><?php echo $value->direccion ?></td>
                   <td><?php echo $value->descripcion ?></td>
                   <?php $id=$value->id; ?>
                   <td style="text-align:center;"><?php echo Html::link("clientes/editar/$id","<span class='glyphicon glyphicon-edit'><span>") ?></td>
                   <td style="text-align:center;"><?php echo Js::link("clientes/eliminar/$id","<span class='glyphicon glyphicon-remove-circle'></span>","¿Esta seguro de eliminar a este cliente?") ?></td>
                </tr>
            <?php endforeach ?>
          </table>
      </fieldset>
    </section>
