<div class="menu" style="height:100%">
	<center><?php echo Html::img("default/logo.jpg","","style='width:50%;margin:auto,padding:20px;'") ?></center>
    
    <div class="info-perfil">
    	<p>
            <?php if (Auth::get("empleado_id")=='0' or Auth::get("empleado_id")==''): ?>
                <?php  if (Auth::get("admin")=='1'): ?>
                    <b><?php echo Html::link("config/index","Menú Principal"); ?></b><br>
                    <b>Usuario:</b> Administrador | <?php echo Html::link("index/logout","Salir"); ?>
                <?php endif ?>
            <?php else: ?>
                <b><?php echo Html::link("config/index","Menú Principal"); ?></b><br>
                <?php $datos = Load::model("empleado")->find(Auth::get("empleado_id")); ?>
                <?php echo Html::img($datos->perfil,"","style='width:50px;margin-left:10px;'") ?>
                <?php echo Auth::get("usuario") ?>
                 | <?php echo Html::link("index/logout","Salir"); ?>
            <?php endif ?>
        </p>
    </div>
    <div class="opt-proyectos">
    	<ul>
    		<li><p>USUARIOS</p></li>
    		<li><?php echo Html::link("personal","<span class='glyphicon glyphicon-list-alt'></span> Personal (Empleados)") ?></li>
    		<li><?php echo Html::link("personal/nuevo","<span class='glyphicon glyphicon-plus-sign'></span> Nuevo Personal") ?></li>
            <li><?php echo Html::link("personal/usuarios","<span class='glyphicon glyphicon-list-alt'></span> Usuarios") ?></li>
            <li><?php echo Html::link("personal/nuevo_usuario","<span class='glyphicon glyphicon-plus-sign'></span> Nuevo Usuario") ?></li>
    	</ul>
    </div>
</div>

